# Change these first
owner: peterablehmann # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Monitoring
    url: https://monitoring.xnee.net
  - name: Kanidm
    url: https://idm.xnee.net
  - name: Paperless
    url: https://paperless.xnee.net
  - name: MNS Map
    url: https://map.mns.xnee.net

status-website:
  cname: upptime.xnee.net
  name: Upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
